version: "3.4"

services:
  postgres:
    container_name: mywallet
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mywallet
      POSTGRES_PASSWORD: mywallet

volumes:
  postgres_data: